# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: NTU4MmNkZjU3MzJlNjg0MWMzOTBlZTkzYTNhOWVjYWU1YzI4Njg0YmFlNGJlN2YyOGU4OWVhNzgyNjUzODc5YTRhMzkyZjI2NmM2NmFmZjM3Mjg3ZDY4MjdmNjI3MDg1YzU3YTVkOTdlMDdlNGFlMDdhNDEwZjg5MTZmNjVlOGM=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
