# Common configuration shared between all applications
configserver:
  name: Docker JHipster Registry
  status: Connected to the JHipster Registry running in Docker

jhipster:
  security:
    authentication:
      jwt:
        # secret key which should be base64 encoded and changed in production
        base64-secret: ODlhNjM4YmMzMGRmMDcwZjY2N2M2ZGJhZGQ0OTQxZTU2MTU2NGFhYzAwNjQ2YTg2NDMxNjM4NzZlOWFlOGNjZWQyNzc0NGRkOTU3ZDI0NDQyN2JmZDNiNzE5MTZlOGI1ZTA3MTA1OTA5NDczY2RlMjc3NTlmY2VlMDFmMDM4OTU=

eureka:
  client:
    service-url:
      defaultZone: http://admin:${jhipster.registry.password}@localhost:8761/eureka/
